---
- name: Copy dockerfile
  ansible.builtin.copy:
    src: files/dockerfile
    dest: /tmp/Dockerfile
    mode: "0644"
  register: influxdb_dockerfile_copy

- name: Create backup script
  become: true
  ansible.builtin.copy:
    src: "files/backup.sh"
    dest: "/tmp/backup.sh"
    mode: "0755"
  register: influxdb_backup_script_copy

- name: Build Docker image
  become: true
  community.docker.docker_image:
    name: "{{ influxdb_backup_image_name }}"
    tag: "{{ influxdb_backup_image_tag }}"
    source: build
    push: false
    build:
      path: /tmp
    force_source: "{{ influxdb_dockerfile_copy.changed or influxdb_backup_script_copy.changed }}"
    state: present
  notify: "Restart {{ influxdb_service_name }}"

- name: Create backup .env file
  become: true
  ansible.builtin.template:
    src: templates/docker-compose/backup-toolkit.env.j2
    dest: "{{ influxdb_service_config_dir }}/backup-toolkit.env"
    group: "{{ influxdb_service_user }}"
    owner: "{{ influxdb_service_user }}"
    mode: "0400"
  notify: "Restart {{ influxdb_service_name }}"

- name: Create backup systemd service file
  become: true
  ansible.builtin.template:
    src: "templates/backup/backup.service.j2"
    dest: /etc/systemd/system/{{ influxdb_service_name }}-backup.service
    owner: root
    group: root
    mode: "0644"
  register: influxdb_backup_service

- name: Create backup systemd timer file
  become: true
  ansible.builtin.template:
    src: "templates/backup/backup.timer.j2"
    dest: /etc/systemd/system/{{ influxdb_service_name }}-backup.timer
    owner: root
    group: root
    mode: "0644"
  register: influxdb_backup_timer

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: influxdb_backup_service.changed or influxdb_backup_timer.changed

- name: Enable and start backup timer
  become: true
  ansible.builtin.systemd:
    name: "{{ influxdb_service_name }}-backup.timer"
    enabled: true
    state: started
  when: influxdb_backup_service.changed or influxdb_backup_timer.changed
