---
- name: Create service user - {{ influxdb_service_user }}
  become: true
  ansible.builtin.user:
    name: "{{ influxdb_service_user }}"
    create_home: false
    comment: "{{ influxdb_service_user }} user with no shell access"
    shell: /bin/false
  register: influxdb_user_result

- name: Create config directory - {{ influxdb_service_config_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ influxdb_service_config_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ influxdb_service_user }}"
    group: "{{ influxdb_service_user }}"

- name: Create data directory - {{ influxdb_service_data_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ influxdb_service_data_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ influxdb_service_user }}"
    group: "{{ influxdb_service_user }}"

- name: Add users to docker group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items:
    - root
    - noxious
    - "{{ influxdb_service_user }}"
