---
influxdb_service_name: influxdb
influxdb_service_version: "2.7.12"
influxdb_service_port: "443"
influxdb_service_data_dir: /var/lib/influxdb
influxdb_service_config_dir: /etc/influxdb
influxdb_service_user: influxdb
influxdb_service_domain: influxdb.local.iamrobertyoung.co.uk
influxdb_service_container_name: influxdb

influxdb_backup_cron: "*-*-* 04:00:00"
influxdb_backup_image_name: backup-toolkit
influxdb_backup_image_tag: local
influxdb_backup_from: /data
influxdb_backup_mosquitto_host: mosquitto.local.iamrobertyoung.co.uk
influxdb_backup_mosquitto_username: "home-assistant"
influxdb_backup_mosquitto_password: "password"
influxdb_backup_bucket_name: "home-server-backup.iamrobertyoung.co.uk"
influxdb_backup_influxdb_host: influxdb
influxdb_backup_influxdb_port: 8086
influxdb_backup_influxdb_org: 0dd8df669872ba9e
influxdb_backup_influxdb_token: password

influxdb_traefik_config_dir: /etc/traefik
